name: Kevin Lehtla | Estonian Web Designer & Front-End Developer
markdown: redcarpet
author: Kevin Lehtla
author_email: bleedeagle@gmail.com
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
baseurl: http://kevinlehtla.ee/
description: Hi, I'm Web Designer & Front-Developer based in Estonia. My passion is in the creative field. I also do Graphic Design.
site.description: Hi, I'm Web Designer & Front-Developer based in Estonia. My passion is in the creative field. I also do Graphic Design.
